### ISSUE TITLE
Static files not served as expected

### ISSUE THREAD

**Issue by sbliven** [3D-Beacons/3d-beacons-client#33]
I wasn't able to access the static files after following the README. I have `ASSETS_URL=/static` in my .env file and the summary endpoint reports `model_url: "/static/cif/P38398.cif"` as expected. However, http://localhost:8000/static/cif/P38398.cif gives a 404 error. The file is present locally at ./data/cif/P38398.cif. Should it be in some other location?

**Comment by sillitoe** [comment]
Thanks for creating this issue and sorry for the huge delay getting back to you.

This was basically an issue with documentation - the API is available on port 80, but we should be using people to go via the nginx frontend which is running on port 80 (this is also responsible for serving static files).

#35 should address this

**Comment by sbliven** [comment]
Thanks @sillitoe. I figured it would be something easy like this. I can confirm it works on port 80.
